name: application_dooz
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  gradient_borders: ^1.0.0
  # confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gradient_colors: ^2.1.1

  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: CA
      fonts:
        - asset: assets/fonts/ca.ttf
        #///
        #///

    - family: DB
      fonts:
        - asset: assets/fonts/db.ttf
        #///
        #///
    - family: DN
      fonts:
        - asset: assets/fonts/dn.ttf
        #///
        #///
    - family: BA
      fonts:
        - asset: assets/fonts/ba.ttf
        #///
        #///
    - family: GI
      fonts:
        - asset: assets/fonts/gi.ttf
        #///
        #///
    - family: SK
      fonts:
        - asset: assets/fonts/sk.ttf
    #     #///
    #     #///
    #     #///
    #     #///
    - family: QT
      fonts:
        - asset: assets/fonts/qt.ttf
    #     #///
    #     #///
    #     #///
    #     #///
    # - family: JM
    #   fonts:
    #     - asset: assets/fonts/jm.ttf
    #     #///
    #     #///
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
