name: application_dooz
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  audioplayers: ^4.1.0

  adivery: ^4.2.0

  confetti: ^0.7.0

  provider: ^6.0.5

  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  gradient_borders: ^1.0.0
  lottie: ^2.3.2
  flutter_svg: ^0.22.0

url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gradient_colors: ^2.1.1

  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - images/
    - assets/lottie/load.json
    - assets/lottie/load2.json
    - assets/lottie/3.json
    - assets/lottie/4.json
    - assets/lottie/5.json
    - assets/lottie/6.json
    - assets/lottie/7.json
    - assets/lottie/8.json
    - assets/lottie/9.json
    - assets/lottie/10.json
    - assets/lottie/11.json
    - assets/lottie/12.json
    - assets/lottie/13.json
    - assets/lottie/14.json
    - assets/lottie/15.json
    - assets/lottie/16.json
    - assets/lottie/17.json
    - assets/lottie/18.json
    - assets/icons/1.svg
    - assets/icons/2.svg
    - assets/icons/3.svg
    - assets/icons/close.svg
    - assets/icons/close1.svg
    - assets/icons/close2.svg
    - assets/icons/close3.svg

  fonts:
    - family: CA
      fonts:
        - asset: assets/fonts/ca.ttf
        #///
        #///

    - family: DB
      fonts:
        - asset: assets/fonts/db.ttf
        #///
        #///
    - family: DN
      fonts:
        - asset: assets/fonts/dn.ttf
        #///
        #///
    - family: BA
      fonts:
        - asset: assets/fonts/ba.ttf
        #///
        #///
    - family: GI
      fonts:
        - asset: assets/fonts/gi.ttf
        #///
        #///
    - family: SK
      fonts:
        - asset: assets/fonts/sk.ttf
    #     #///
    #     #///
    #     #///
    #     #///
    - family: QT
      fonts:
        - asset: assets/fonts/qt.ttf
    #     #///
    #     #///
    #     #///
    #     #///
    - family: DV
      fonts:
        - asset: assets/fonts/dv.ttf
    #     #///
    #     #///
    - family: MKTB
      fonts:
        - asset: assets/fonts/mktb.ttf
    #     #///
    #     #///
    - family: IRAN
      fonts:
        - asset: assets/fonts/iran.ttf
    #     #///
    #     #///
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
